### ISSUE TITLE
META TITLE

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ehandel.com.pl#10]
''Udostępniając go w mediach społecznościowych zauważyłem dość istotną usterkę w Państwa serwisie.
Otóż nie wstawia on tytułów artykułów w META TITLE.
META TITLE dla każdej strony jest identyczny - "ehandel.com.pl".''

**Comment by az** [comment]
![Sharing Debugger - Facebook for Developers 2021-03-17 11-04-54](https://user-images.githubusercontent.com/2198/111450389-9db45600-8710-11eb-9956-e098e3c9a9fb.png)

fixed :)
